apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: todo-chatbot
    component: backend
spec:
  type: ClusterIP
  selector:
    app: todo-chatbot
    component: backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
