apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data
  labels:
    app: todo-chatbot
    component: backend
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
