apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: todo-chatbot
    component: frontend
spec:
  type: LoadBalancer
  selector:
    app: todo-chatbot
    component: frontend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
