# Secret Template - DO NOT commit actual values to version control
# Create actual secret using: kubectl create secret generic todo-chatbot-secret --from-env-file=.env

apiVersion: v1
kind: Secret
metadata:
  name: todo-chatbot-secret
  labels:
    app: todo-chatbot
type: Opaque
stringData:
  # Replace these placeholder values with actual credentials
  # In production, use external secret management (e.g., Sealed Secrets, External Secrets Operator)
  DATABASE_URL: "postgresql://user:password@host:5432/database"
  OPENAI_API_KEY: "sk-placeholder-key"
  NEON_API_KEY: "placeholder-neon-key"
