openapi: 3.1.0
info:
  title: Todo Chatbot API
  description: FastAPI backend endpoints for OpenAI ChatKit integration
  version: 0.1.0
  contact:
    name: Todo Chatbot Team

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.todo-chatbot.example.com
    description: Production server

paths:
  /chatkit/threads:
    post:
      operationId: create_thread
      summary: Create new conversation thread
      description: Creates a new conversation thread for the authenticated user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 200
                  nullable: true
                  description: Optional thread title
      responses:
        '200':
          description: Thread created successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - thread_id
                  - created_at
                properties:
                  thread_id:
                    type: string
                    format: uuid
                    description: Unique thread identifier
                  title:
                    type: string
                    nullable: true
                  created_at:
                    type: string
                    format: date-time
        '401':
          description: Unauthorized (missing or invalid token)
        '500':
          description: Server error

  /chatkit/threads/{thread_id}:
    get:
      operationId: get_thread
      summary: Get thread details
      description: Retrieves conversation thread details and message history
      security:
        - bearerAuth: []
      parameters:
        - name: thread_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Thread identifier
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
          description: Maximum number of messages to return
        - name: before
          in: query
          schema:
            type: string
            format: date-time
          description: Return messages before this timestamp (for pagination)
      responses:
        '200':
          description: Thread retrieved successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - thread_id
                  - messages
                properties:
                  thread_id:
                    type: string
                    format: uuid
                  title:
                    type: string
                    nullable: true
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized
        '404':
          description: Thread not found or does not belong to user
        '500':
          description: Server error

  /chatkit/threads/{thread_id}/messages:
    post:
      operationId: send_message
      summary: Send message to thread
      description: Sends a user message to the conversation thread and streams AI agent response
      security:
        - bearerAuth: []
      parameters:
        - name: thread_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Thread identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - text
              properties:
                text:
                  type: string
                  minLength: 1
                  maxLength: 2000
                  description: User message content
                attachments:
                  type: array
                  items:
                    type: object
                    properties:
                      file_url:
                        type: string
                        format: uri
                      name:
                        type: string
                      type:
                        type: string
                  description: Optional file attachments (future enhancement)
      responses:
        '200':
          description: Message sent, streaming response
          content:
            text/event-stream:
              schema:
                type: string
                description: Server-Sent Events stream with agent response chunks
              example: |
                data: {"type": "message_start", "message_id": "msg_123"}

                data: {"type": "content_delta", "delta": "I'll help"}

                data: {"type": "content_delta", "delta": " you create"}

                data: {"type": "content_delta", "delta": " that task."}

                data: {"type": "message_end", "message_id": "msg_123"}

        '401':
          description: Unauthorized
        '404':
          description: Thread not found
        '400':
          description: Invalid input (empty message, message too long, etc.)
        '429':
          description: Rate limit exceeded
        '500':
          description: Server error

  /chatkit/threads/{thread_id}/messages/{message_id}:
    get:
      operationId: get_message
      summary: Get message by ID
      description: Retrieves a specific message from the conversation thread
      security:
        - bearerAuth: []
      parameters:
        - name: thread_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: message_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Message retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized
        '404':
          description: Message or thread not found
        '500':
          description: Server error

  /auth/register:
    post:
      operationId: register_user
      summary: Register new user
      description: Creates a new user account with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 255
                  description: User email address
                password:
                  type: string
                  minLength: 8
                  maxLength: 128
                  description: User password (min 8 characters)
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - user_id
                  - email
                  - access_token
                properties:
                  user_id:
                    type: string
                    format: uuid
                  email:
                    type: string
                  access_token:
                    type: string
                    description: JWT access token
        '400':
          description: Invalid input (invalid email, weak password, etc.)
        '409':
          description: Email already registered
        '500':
          description: Server error

  /auth/login:
    post:
      operationId: login_user
      summary: Login user
      description: Authenticates user with email and password, returns JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                required:
                  - user_id
                  - email
                  - access_token
                properties:
                  user_id:
                    type: string
                    format: uuid
                  email:
                    type: string
                  access_token:
                    type: string
                    description: JWT access token
        '401':
          description: Invalid credentials
        '500':
          description: Server error

  /auth/me:
    get:
      operationId: get_current_user
      summary: Get current user
      description: Returns authenticated user's profile information
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile retrieved
          content:
            application/json:
              schema:
                type: object
                required:
                  - user_id
                  - email
                  - created_at
                properties:
                  user_id:
                    type: string
                    format: uuid
                  email:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  is_active:
                    type: boolean
        '401':
          description: Unauthorized
        '500':
          description: Server error

  /health:
    get:
      operationId: health_check
      summary: Health check
      description: Returns server health status
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                properties:
                  status:
                    type: string
                    enum: [healthy]
                  database:
                    type: string
                    enum: [connected, disconnected]
                  version:
                    type: string

components:
  schemas:
    Message:
      type: object
      required:
        - message_id
        - role
        - content
        - created_at
      properties:
        message_id:
          type: string
          format: uuid
          description: Unique message identifier
        role:
          type: string
          enum: [user, assistant]
          description: Message sender role
        content:
          type: string
          description: Message content
        created_at:
          type: string
          format: date-time
          description: Message timestamp

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error type
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          nullable: true
          description: Additional error details

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /auth/login or /auth/register
